pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/FernandoSolisPaz/entrega_1_Tingeso']])
                dir("Evaluacion_1_Tingeso/FontEnd/vite-project"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("Evaluacion_1_Tingeso/FontEnd/vite-project"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t fernandosolispaz/frontend ."
                            bat "docker push fernandosolispaz/frontend"
                        }
                    }                    
                }
            }
        }
    }
}