version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: auto-fix-nginx-backend-container
    restart: always
    ports:
      - 8090:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - auto-fix-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: auto-fix-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - auto-fix-frontend-network
    depends_on:      
      - react1
      - react2
      - react3
  postgres:
    container_name: auto-fix-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - auto-fix-postgres-volume:/var/lib/postgresql/data
    networks:
      - auto-fix-backend-network
    environment:      
      POSTGRES_DB: tingeso
      POSTGRES_PASSWORD: 1234
    ports:
      - 5435:5432      
  spring1:
    container_name: auto-fix-backend-container-1
    image: fernandosolispaz/evaluacion_1_tingeso
    ports:
      - 8091:8090
    environment:
      DB_HOST: auto-fix-postgres-container
      PORT: 5432
      USER: postgres
      PASSWORD: 1234
    networks:
      - auto-fix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: auto-fix-backend-container-2
    image: fernandosolispaz/evaluacion_1_tingeso
    ports:
      - 8092:8090
    environment:
      DB_HOST: auto-fix-postgres-container
      PORT: 5432
      USER: postgres
      PASSWORD: 1234
    networks:
      - auto-fix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: auto-fix-backend-container-3
    image: fernandosolispaz/evaluacion_1_tingeso
    ports:
      - 8093:8090
    environment:
      DB_HOST: auto-fix-postgres-container
      PORT: 5432
      USER: postgres
      PASSWORD: 1234
    networks:
      - auto-fix-backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: auto-fix-frontend-container-1
    image: fernandosolispaz/frontend
    ports:
      - 3001:3000
    networks:
      - auto-fix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: auto-fix-frontend-container-2
    image: fernandosolispaz/frontend
    ports:
      - 3002:3000
    networks:
      - auto-fix-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: auto-fix-frontend-container-3
    image: fernandosolispaz/frontend
    networks:
      - auto-fix-frontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  auto-fix-postgres-volume:
networks:
  auto-fix-frontend-network:
  auto-fix-backend-network: